add intake subsystem test
sneakysnakesfrc/robot-2021-offseason pull request #11
Opened 2021-08-06 20:23 UTC by KahramanAkyuz

2021-08-07 15:23 UTC, vatanaksoytezer requested changes
Ufak birkaç şey dışında güzel gözüküyor onları da hallettin mi mergeleyebiliriz

2021-08-07 15:23 UTC, vatanaksoytezer commented on src/test/java/frc/robot/subsystems/Intaketest.java
> +        assert HAL.initialize(500, 0);
Buraya emreninki gibi bir comment yazalım (bkz. #10)

2021-08-07 15:23 UTC, vatanaksoytezer commented on .pre-commit-config.yaml
> -      args: [--autofix]
Bunu geri ekleyelim @emrecandabak #10'da söylediğim üzere başka bir PR açacak, bunun için

2021-08-07 15:23 UTC, vatanaksoytezer commented on src/test/java/frc/robot/subsystems/Intaketest.java
> +    public void intakeup() {
test fonksiyonlarını testIntakeUp gibi yapabiliriz, daha belirgin olur. Lütfen camelCase kullanalım

2021-08-07 15:23 UTC, vatanaksoytezer commented on src/test/java/frc/robot/subsystems/Intaketest.java
> +    public void intakedown(){
fonksiyon ismi için yukarıda yazdığım aynı şey geçerli.

2021-08-09 19:05 UTC, KahramanAkyuz commented
@vatanaksoytezer  abi düzelttim dediklerini

2021-08-09 19:19 UTC, vatanaksoytezer approved these changes

2021-08-09 19:19 UTC, merged